# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa6b948c66bf46f987a3e3007d9b44b993af3d26de62ee619969073c008c578d035042f2ae7679f289a9709dc33cddee6ab4a8db71380be7c57faa663406f370

test:
  secret_key_base: ce7a4956f9f4c3614d98556317cee487a49b54e6722ffa80eb00f3f14474266ce892c6534b03b0e58fec51b6b22aed863e56964943ce9eb925edc7b00d03c63b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
